### ISSUE TITLE
JWT stops working when upgrading from v0.0.13 to v0.1.0

### ISSUE THREAD

**Issue by yunjiali** [waterlock/waterlock#102]
My old programme (v0.0.13 I think) used to work well following /auth/login and /user/jwt. But when I upgrade to v0.1.0 the /user/jwt constantly gives me:

```{undefined: somenumber}```

I think this is because the code in [jwt.js](https://github.com/waterlock/waterlock/blob/ee0b8933651e73b357607d08cb39e3fbc2f80444/lib/controllers/actions/jwt.js} has been changed to include some customisation:

```
    result[waterlock.config.jsonWebTokens.tokenProperty] = jwtData.token;
    result[waterlock.config.jsonWebTokens.expiresProperty] = jwtData.expires;
```

However, in the old version of waterlock, tokenProperty and expiresProperty are not defined in waterlock.js. So it's better to remind people to add it after upgrading or add a if condition before applying ```tokenProperty``` and ```expiresProperty``` in case those two properties are not there. Not sure if I get this right?
