### ISSUE TITLE
waterlock.User.findOne is not a function

### ISSUE THREAD

**Issue by MedoHaleem** [waterlock/waterlock#136]
This happens after upgrading from sails 0.11.2 to 0.12.3 and typing sails lift, even rolling back doesn't fix the issue, I deleted the whole node_modules, cleared npm cache and reinstalled everything, yet still experience the problem.

here full stack trace:

```

   waterlock.User.findOne(cri).populate('auth').populate('role')
                     ^

TypeError: waterlock.User.findOne is not a function
    at Object.findUser (/vagrant/sharpone_app/node_modules/waterlock/lib/engine.js:48:22)
    at GoogleOAuth2.accessTokenResponse [as _tokenCallback] (/vagrant/sharpone_app/node_modules/waterlock-google-auth/lib/controllers/actions/oauth2.js:42:22)
    at /vagrant/sharpone_app/node_modules/waterlock-google-auth/lib/google-oauth2.js:142:17
    at /vagrant/sharpone_app/node_modules/waterlock-google-auth/lib/google-oauth2.js:180:14
    at /vagrant/sharpone_app/node_modules/waterlock-google-auth/lib/google-oauth2.js:225:7
    at /vagrant/sharpone_app/node_modules/sails/node_modules/async/lib/async.js:52:16
    at /vagrant/sharpone_app/node_modules/sails/node_modules/async/lib/async.js:1204:30
    at Request._callback (/vagrant/sharpone_app/node_modules/waterlock-google-auth/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/vagrant/sharpone_app/node_modules/waterlock-google-auth/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/vagrant/sharpone_app/node_modules/waterlock-google-auth/node_modules/google-auth-library/node_modules/request/request.js:1057:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/vagrant/sharpone_app/node_modules/waterlock-google-auth/node_modules/google-auth-library/node_modules/request/request.js:1003:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

this was my custom function where we find by user email, even without my function same error happens with Auth

```
getbaseurl for more info.
/vagrant/sharpone_app/node_modules/waterlock/lib/engine.js:114
      waterlock.Auth.findOrCreate(criteria, attributes)
                     ^

TypeError: waterlock.Auth.findOrCreate is not a function
    at Object.findOrCreateAuth (/vagrant/sharpone_app/node_modules/waterlock/lib/engine.js:114:22)
    at GoogleOAuth2.accessTokenResponse [as _tokenCallback] (/vagrant/sharpone_app/node_modules/waterlock-google-auth/lib/controllers/actions/oauth2.js:54:21)
    at GoogleOAuth2._tokenExchangeCallback (/vagrant/sharpone_app/node_modules/waterlock-google-auth/lib/google-oauth2.js:128:21)
    at Request.self.callback (/vagrant/sharpone_app/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/vagrant/sharpone_app/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/vagrant/sharpone_app/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```
